
drop table "SYSTEM"."PEOPLE" cascade constraints PURGE;
drop table "SYSTEM"."LISTING_CATEGORY" cascade constraints PURGE;
drop table "SYSTEM"."RENTAL_BASIS" cascade constraints PURGE;
drop table "SYSTEM"."ADDRESS_STATE" cascade constraints PURGE;
drop table "SYSTEM"."ADDRESS_COUNTRY" cascade constraints PURGE;
drop table "SYSTEM"."ADDRESS_CITY" cascade constraints PURGE;
drop table "SYSTEM"."USER_ADDRESS" cascade constraints PURGE;
drop table "SYSTEM"."LISTINGS" cascade constraints PURGE;
drop table "SYSTEM"."EMPLOYEE_ADDRESS" cascade constraints PURGE;
drop table "SYSTEM"."DEAL_STATUS" cascade constraints PURGE;
drop table "SYSTEM"."DEALS" cascade constraints PURGE;
drop table "SYSTEM"."DESIGNATION" cascade constraints PURGE;
drop table "SYSTEM"."CURRENT_STATUS" cascade constraints PURGE;
drop table "SYSTEM"."ORDER_STATUS" cascade constraints PURGE;
drop table "SYSTEM"."EMPLOYEE" cascade constraints PURGE;

